# Generated by Django 3.1.3 on 2020-11-19 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_blog_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='para1',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='para2',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='para3',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='para4',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='para5',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='subheading1',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='subheading2',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='subheading3',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='subheading4',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='subheading5',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='thumbnail',
            field=models.ImageField(default=1, upload_to='pics'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='urllink',
            field=models.TextField(null=True),
        ),
    ]
